# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='comm',
            field=models.CharField(max_length=160),
        ),
    ]
